--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: buddyrequest; Type: TABLE; Schema: public; Owner: kper
--

CREATE TABLE public.buddyrequest (
    id bigint NOT NULL,
    confirmed boolean NOT NULL,
    email character varying(255) NOT NULL,
    exam_date date NOT NULL,
    on_create date NOT NULL,
    token character varying(255) NOT NULL,
    course_id bigint
);


ALTER TABLE public.buddyrequest OWNER TO kper;

--
-- Name: buddyrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: kper
--

ALTER TABLE public.buddyrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buddyrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course; Type: TABLE; Schema: public; Owner: kper
--

CREATE TABLE public.course (
    id bigint NOT NULL,
    name character varying(1024) NOT NULL
);


ALTER TABLE public.course OWNER TO kper;

--
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: kper
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: match; Type: TABLE; Schema: public; Owner: kper
--

CREATE TABLE public.match (
    id bigint NOT NULL,
    buddy1 character varying(255) NOT NULL,
    buddy2 character varying(255) NOT NULL,
    exam_date date NOT NULL,
    on_create date NOT NULL,
    course_id bigint
);


ALTER TABLE public.match OWNER TO kper;

--
-- Name: match_id_seq; Type: SEQUENCE; Schema: public; Owner: kper
--

ALTER TABLE public.match ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.match_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: buddyrequest; Type: TABLE DATA; Schema: public; Owner: kper
--

COPY public.buddyrequest (id, confirmed, email, exam_date, on_create, token, course_id) FROM stdin;
\.


--
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: kper
--

COPY public.course (id, name) FROM stdin;
\.


--
-- Data for Name: match; Type: TABLE DATA; Schema: public; Owner: kper
--

COPY public.match (id, buddy1, buddy2, exam_date, on_create, course_id) FROM stdin;
\.


--
-- Name: buddyrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: kper
--

SELECT pg_catalog.setval('public.buddyrequest_id_seq', 1, false);


--
-- Name: course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: kper
--

SELECT pg_catalog.setval('public.course_id_seq', 1, false);


--
-- Name: match_id_seq; Type: SEQUENCE SET; Schema: public; Owner: kper
--

SELECT pg_catalog.setval('public.match_id_seq', 1, false);


--
-- Name: buddyrequest buddyrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: kper
--

ALTER TABLE ONLY public.buddyrequest
    ADD CONSTRAINT buddyrequest_pkey PRIMARY KEY (id);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: kper
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: match match_pkey; Type: CONSTRAINT; Schema: public; Owner: kper
--

ALTER TABLE ONLY public.match
    ADD CONSTRAINT match_pkey PRIMARY KEY (id);


--
-- Name: buddyrequest fkcb4271n60us2hmtvxc2crf2fw; Type: FK CONSTRAINT; Schema: public; Owner: kper
--

ALTER TABLE ONLY public.buddyrequest
    ADD CONSTRAINT fkcb4271n60us2hmtvxc2crf2fw FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: match fkml026i6piknhnirhf4ydvm0me; Type: FK CONSTRAINT; Schema: public; Owner: kper
--

ALTER TABLE ONLY public.match
    ADD CONSTRAINT fkml026i6piknhnirhf4ydvm0me FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- PostgreSQL database dump complete
--

