INSERT INTO course (name) VALUES ('030133 VO Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030164 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030636 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030638 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030639 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030640 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030641 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030642 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030643 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030646 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030647 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030648 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030649 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030650 UE Übung zur Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('030085 KU Kurs Privatrechtlicher Teil der Einführung - Falllösung');
INSERT INTO course (name) VALUES ('030002 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030028 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030037 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030043 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030080 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030086 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030137 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030182 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030458 PF STEOP: Pflichtübung Romanistische Fundamente');
INSERT INTO course (name) VALUES ('030010 PF STEOP: Pflichtübung aus Rechts- und Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030152 PF StEOP: Pflichtübung aus Rechts- und Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030247 PF StEOP: Pflichtübung aus Rechts- und Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030004 KU Romanistische Fundamente: Sachenrecht und Grundlagen');
INSERT INTO course (name) VALUES ('030041 VO Römische Rechtsgeschichte und ausgewählte Gebiete des Personen- und Familienrechts');
INSERT INTO course (name) VALUES ('030042 KU Romanistische Fundamente: Schuldrecht und Grundlagen');
INSERT INTO course (name) VALUES ('030269 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030272 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030392 KU Die römische Gesellschaft');
INSERT INTO course (name) VALUES ('030664 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030672 KU Workshop zum Verfassen juristischer Texte');
INSERT INTO course (name) VALUES ('030027 UE Übung Romanistische Fundamente - Schuldrecht');
INSERT INTO course (name) VALUES ('030031 UE Übung Romanistische Fundamente - Sachenrecht');
INSERT INTO course (name) VALUES ('030081 UE Übung Romanistische Fundamente - Schuldrecht');
INSERT INTO course (name) VALUES ('030178 UE Übung Romanistische Fundamente - Sachenrecht');
INSERT INTO course (name) VALUES ('030180 UE Übung Romanistische Fundamente (Schuldrecht)');
INSERT INTO course (name) VALUES ('030183 UE Übung Romanistische Fundamente (Sachenrecht und Schuldrecht)');
INSERT INTO course (name) VALUES ('030186 UE Übung Romanistische Fundamente - Schuldrecht');
INSERT INTO course (name) VALUES ('030275 MC International Roman Law Moot Court');
INSERT INTO course (name) VALUES ('030524 SE Aktuelle Forschungen im Bereich des Röm. Rechts u. seiner Fortwirkung in den geltenden Privatrechten');
INSERT INTO course (name) VALUES ('030549 SE Seminar aus Römischem Recht - Kaufen wie in Troja');
INSERT INTO course (name) VALUES ('030054 VO Juden und Judenheit(en) in Österreich. Eine Rechtsgeschichte.');
INSERT INTO course (name) VALUES ('030120 VO Rechts- und Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030376 VO Rechts- und Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030420 VO Geschichte der Grund- und Menschenrechte');
INSERT INTO course (name) VALUES ('030007 UE Übung aus Rechts- und Verfassungsgeschichte (ausgewählte Schwerpunkte aus dem gesamten Fach)');
INSERT INTO course (name) VALUES ('030018 UE Übung aus Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030046 UE Übung aus Privatrechtsgeschichte');
INSERT INTO course (name) VALUES ('030131 UE Übung aus Rechts- und Verfassungsgeschichte (ausgewählte Schwerpunkte aus dem gesamten Fach)');
INSERT INTO course (name) VALUES ('030211 UE Übung aus Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030293 UE Übung aus Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030344 UE Übung aus Privatrechtsgeschichte');
INSERT INTO course (name) VALUES ('030407 UE Übung aus Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030412 UE Übung aus Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030078 SE Seminar: Rechtsgeschichte der Wirtschaft');
INSERT INTO course (name) VALUES ('030256 SE Seminar aus europäischer und vergleichender Rechtsgeschichte für Diplomand*innen u. Dissertant*innen');
INSERT INTO course (name) VALUES ('030314 SE Nationsbildung und Verfassungsentwicklung in Europa 2. Teil');
INSERT INTO course (name) VALUES ('030393 SE Seminar aus Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030418 SE Seminar: Große Prozesse');
INSERT INTO course (name) VALUES ('030504 SE Seminar aus Arbeitsrecht und Rechtsgeschichte');
INSERT INTO course (name) VALUES ('030528 SE Seminar: Normsetzung und Rechtsprechung im Nationalsozialismus. Ausgewählte Aspekte');
INSERT INTO course (name) VALUES ('030560 SE Fritz Bauer oder: Auschwitz vor Gericht');
INSERT INTO course (name) VALUES ('030566 MC Ius Commune Moot Court');
INSERT INTO course (name) VALUES ('030684 SE SE ohne Generalthema');
INSERT INTO course (name) VALUES ('030707 SE Seminar aus Rechts- und Verfassungsgeschichte: Rechtspolitische Filme der Zwischenkriegszeit');
INSERT INTO course (name) VALUES ('030038 KU Geschichte des österreichischen Justizrechts - Geltung und Ausstrahlung nach 1918');
INSERT INTO course (name) VALUES ('030141 KU Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030299 KU Rechtsgeschichte des vormodernen Europa');
INSERT INTO course (name) VALUES ('030559 KU Globalisierung und Rechtspluralismus');
INSERT INTO course (name) VALUES ('030261 RE Repetitorium aus Rechts- und Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030282 RE Repetitorium aus Rechts- und Verfassungsgeschichte');
INSERT INTO course (name) VALUES ('030475 UE Übung FÜM I - Europarechtlicher Teil');
INSERT INTO course (name) VALUES ('030508 UE Übung FÜM I - Europarechtlicher Teil');
INSERT INTO course (name) VALUES ('030477 VO Grundlagen des Völkerrechts');
INSERT INTO course (name) VALUES ('030532 UE Vorbereitung auf die FÜM I - Völkerrechtlicher Teil');
INSERT INTO course (name) VALUES ('030633 UE Vorbereitung auf die FÜM I - Völkerrechtlicher Teil');
INSERT INTO course (name) VALUES ('030104 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030162 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030209 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030279 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030409 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030556 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030657 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030663 UE Anfängerübung zur Falllösung aus Bürgerlichem Recht');
INSERT INTO course (name) VALUES ('030022 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030075 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030089 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030106 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030136 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030242 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030283 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030294 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030351 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030434 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030466 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030467 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030470 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030485 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030486 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030487 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030489 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030493 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030494 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030496 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030511 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030599 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030607 UE Anfängerübung zur Falllösung aus Strafrecht');
INSERT INTO course (name) VALUES ('030040 KU Juristische Recherche');
INSERT INTO course (name) VALUES ('030367 KU Juristische Recherche im grenzüberschreitenden Kontext');
INSERT INTO course (name) VALUES ('030001 VO Vorlesung Strafrecht: Allgemeiner Teil I');
INSERT INTO course (name) VALUES ('030156 VO Vorlesung Strafrecht: Besonderer Teil - Lehre von den Delikten');
INSERT INTO course (name) VALUES ('030059 UE Übung aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030221 UE Übung aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030288 UE Übung aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030404 UE Übung aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030473 UE Übung aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030507 UE Übung aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030617 UE Übung aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030189 VO Konversatorium: Prüfungswichtige Fragen des Strafprozessrechts und des AT II');
INSERT INTO course (name) VALUES ('030049 KU IT-Strafrecht I');
INSERT INTO course (name) VALUES ('030169 KU Privatissimum aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030199 KU Course: "European Criminal Law"');
INSERT INTO course (name) VALUES ('030215 KU Drogenkriminalität in Theorie und Praxis');
INSERT INTO course (name) VALUES ('030265 KU Aktuelle Kriminalpolitik');
INSERT INTO course (name) VALUES ('030305 KU Wirtschaftsstrafrecht in der Praxis');
INSERT INTO course (name) VALUES ('030384 KU White-Collar Crime, Compliance &amp; Investigations');
INSERT INTO course (name) VALUES ('030478 KU Gerichts-Praxis: Die Tätigkeit der Richter*innen und Staatsanwält*innen');
INSERT INTO course (name) VALUES ('030480 KU Allgemeiner Teil I: Der Schlüssel zum Strafrecht - Basics, Highlights, Updates');
INSERT INTO course (name) VALUES ('030484 KU Falltraining Strafrecht intensiv');
INSERT INTO course (name) VALUES ('030138 SE Seminar aus Finanzstrafrecht: Tax and Crime');
INSERT INTO course (name) VALUES ('030147 SE Seminar aus Kriminologie und Strafrecht');
INSERT INTO course (name) VALUES ('030226 SE Seminar "Korruption und Amtsmissbrauch"');
INSERT INTO course (name) VALUES ('030324 SE Aktuelle Fragen zum Strafprozessrecht');
INSERT INTO course (name) VALUES ('030361 SE Strafrechtliche Grenzen investigativen Journalismus');
INSERT INTO course (name) VALUES ('030490 SE Undercover: Geheime Ermittlungsmaßnahmen im Strafprozess');
INSERT INTO course (name) VALUES ('030501 SE Seminar zur Ausstellung "Kunst und Strafrecht"');
INSERT INTO course (name) VALUES ('030503 SE Grenzüberschreitende Organisierte Kriminalität: Illegaler Waffen- und Kriegsmaterialhandel');
INSERT INTO course (name) VALUES ('030527 SE Seminar aus Straf- und Strafprozessrecht: Rechtsprechung und Lehre im Dialog');
INSERT INTO course (name) VALUES ('030611 SE Seminar aus Strafrecht und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030058 VO Schuldrecht Allgemeiner Teil');
INSERT INTO course (name) VALUES ('030096 VO Schuldrecht, Besonderer Teil-Vertragsverhältnisse');
INSERT INTO course (name) VALUES ('030276 VO Allgemeiner Teil');
INSERT INTO course (name) VALUES ('030558 VO Schuldrecht Besonderer Teil: gesetzliche Schuldverhältnisse');
INSERT INTO course (name) VALUES ('030065 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030073 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030159 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030266 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030364 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030439 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030453 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030569 UE Übung aus Zivilrecht');
INSERT INTO course (name) VALUES ('030063 KU Klausurenkurs aus Privatrecht');
INSERT INTO course (name) VALUES ('030377 KU Klausurenkurs aus Privatrecht');
INSERT INTO course (name) VALUES ('030523 KU Klausurenkurs aus Privatrecht');
INSERT INTO course (name) VALUES ('030546 KU Klausurenkurs aus Privatrecht');
INSERT INTO course (name) VALUES ('030113 VO Repetitorium aus Zivilrecht');
INSERT INTO course (name) VALUES ('030114 VO Repetitorium aus Zivilrecht');
INSERT INTO course (name) VALUES ('030497 RE Repetitorium aus IPR, UN-Kaufrecht');
INSERT INTO course (name) VALUES ('030289 KU Allgemeine vertragsrechtliche Probleme, dargestellt an Beispielen aus dem Vertragsversicherungsrecht');
INSERT INTO course (name) VALUES ('030095 SE Seminar aus Zivilrecht');
INSERT INTO course (name) VALUES ('030255 SE Seminar aus Zivilrecht, IPR und Rechtsvergleichung');
INSERT INTO course (name) VALUES ('030465 SE Die Corona-Pandemie aus zivil- und datenschutzrechtlicher Sicht');
INSERT INTO course (name) VALUES ('030509 SE Seminar aus Zivilrecht und IPR / Civilno pravo in mednarodno zasebno pravo');
INSERT INTO course (name) VALUES ('030596 SE Rechtsdurchsetzung im Verbraucherrecht');
INSERT INTO course (name) VALUES ('030099 KU Zivilrechtliche Aspekte des Gleichbehandlungsrechts');
INSERT INTO course (name) VALUES ('030297 KU Public Markets, Securities Regulation and Corporate Governance');
INSERT INTO course (name) VALUES ('030307 KU Internationales Vertragsrecht und vereinheitlichtes Kaufrecht');
INSERT INTO course (name) VALUES ('030478 KU Gerichts-Praxis: Die Tätigkeit der Richter*innen und Staatsanwält*innen');
INSERT INTO course (name) VALUES ('030548 KU Bis Richter oder Tod Euch scheiden');
INSERT INTO course (name) VALUES ('030411 MC Moot Court Zivilrecht');
INSERT INTO course (name) VALUES ('030009 VO Unternehmensrecht');
INSERT INTO course (name) VALUES ('030097 VO Gesellschaftsrecht');
INSERT INTO course (name) VALUES ('030101 VO Lauterkeitsrecht und Grundzüge des Immaterialgüterrechts');
INSERT INTO course (name) VALUES ('030158 VO Schwerpunkte des Kapitalgesellschaftsrechts (vertiefend)');
INSERT INTO course (name) VALUES ('030631 VO Internationales Unternehmensrecht');
INSERT INTO course (name) VALUES ('030083 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030111 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030291 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030295 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030310 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030340 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030381 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030383 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030632 UE Übung aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030347 KU Klausurenkurs aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030391 KU Klausurenkurs aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030595 KU Klausurenkurs aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030668 KU Klausurenkurs aus Unternehmensrecht');
INSERT INTO course (name) VALUES ('030127 VO Intensivvorbereitung aus Unternehmens- und Gesellschaftsrecht');
INSERT INTO course (name) VALUES ('030145 VO Intensivvorbereitung aus Unternehmensrecht/Gesellschaftsrecht AT und Personengesellschaften');
INSERT INTO course (name) VALUES ('030268 VO Intensivvorbereitung aus Unternehmens- und Gesellschaftsrecht');
INSERT INTO course (name) VALUES ('030604 VO Intensivvorbereitung aus Unternehmes- und Gesellschaftsrecht');
INSERT INTO course (name) VALUES ('030192 KU Corporate Governance bei börsennotierten Aktiengesellschaften');
INSERT INTO course (name) VALUES ('030216 KU Gesellschaftsrecht in höchstgerichtlicher Rechtsprechung');
INSERT INTO course (name) VALUES ('030217 KU Comparative Corporate Law Theory and Economic Analysis');
INSERT INTO course (name) VALUES ('030249 KU Europäisches und österreichisches Kartellrecht');
INSERT INTO course (name) VALUES ('030681 KU M &amp; A International Part I (Corporate Law)');
INSERT INTO course (name) VALUES ('030737 KU Case studies: Mergers &amp; Acquisitions');
INSERT INTO course (name) VALUES ('030047 SE Seminar aus Unternehmens- und Wirtschaftsrecht');
INSERT INTO course (name) VALUES ('030207 SE Seminar aus Unternehmensrecht für Diplomand*innen');
INSERT INTO course (name) VALUES ('030252 SE Seminar Unternehmens- und Wirtschaftsrecht');
INSERT INTO course (name) VALUES ('030312 SE Seminar aus Unternehmens- und Wirtschaftsrecht');
INSERT INTO course (name) VALUES ('030345 SE Seminar Wirtschaftsrecht');
INSERT INTO course (name) VALUES ('030419 SE Seminar aus Unternehmens- und Wirtschaftsrecht (Fachseminar)');
INSERT INTO course (name) VALUES ('030512 SE Seminar aus Unternehmens- und Wirtschaftsrecht: Schwerpunkt Recht der Sportvereine');
INSERT INTO course (name) VALUES ('030593 SE Rechtsvergleichende und ökonomische Analyse des Gesellschafts- und Kapitalmarktrechts');
INSERT INTO course (name) VALUES ('040083 SE Seminar Wirtschaftsrecht (MA)');
INSERT INTO course (name) VALUES ('040198 SE Seminar Wirtschaftsrecht (MA)');
INSERT INTO course (name) VALUES ('030003 VO Zivilverfahrensrecht I (Erkenntnisverfahren): 1. Teil, Zivilprozess');
INSERT INTO course (name) VALUES ('030116 VO Zivilverfahrensrecht I (Erkenntnisverfahren): 2. Teil, Außerstreitverfahren');
INSERT INTO course (name) VALUES ('030403 VO International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030167 UE Übung aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030195 UE Übung aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030614 UE Übung aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030717 UE Übung aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030749 UE Übung aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030148 VO Repetitorium aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030343 VO Repetitorium aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030005 SE Moot Court aus International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030287 SE Law and Literature: Margaret Atwood, Der Report der Magd (1985) und Die Zeuginnen (2019)');
INSERT INTO course (name) VALUES ('030298 SE Seminar aus Zivilverfahrensrecht - Schwerpunkt: International Dispute Resolution');
INSERT INTO course (name) VALUES ('030386 SE Seminar aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030436 SE Seminar aus Zivilverfahrensrecht: Schwerpunkt: Insolvenz- und Restrukturierungsrecht');
INSERT INTO course (name) VALUES ('030520 SE Seminar aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030573 SE Seminar aus Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('030033 KU Rechtliche Aspekte der außergerichtlichen Konfliktregelung insbesondere Mediation und Schlichtung');
INSERT INTO course (name) VALUES ('030045 KU Materielles Insolvenzrecht mit Schwerpunkt Anfechtungsrecht');
INSERT INTO course (name) VALUES ('030478 KU Gerichts-Praxis: Die Tätigkeit der Richter*innen und Staatsanwält*innen');
INSERT INTO course (name) VALUES ('030005 SE Moot Court aus International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030051 VO Arbeitsrecht und Sozialrecht: Teil 1 - Kollektives Arbeitsrecht');
INSERT INTO course (name) VALUES ('030179 VO Arbeitsrecht und Sozialrecht: Teil 2 - Individualarbeitsrecht');
INSERT INTO course (name) VALUES ('030280 VO Arbeitsrecht und Sozialrecht: Teil 3 - Sozialrecht');
INSERT INTO course (name) VALUES ('030011 UE Übung aus Arbeitsrecht und Sozialrecht');
INSERT INTO course (name) VALUES ('030296 UE Übung aus Arbeitsrecht und Sozialrecht');
INSERT INTO course (name) VALUES ('030306 UE Übung aus Arbeitsrecht und Sozialrecht');
INSERT INTO course (name) VALUES ('030313 UE Übung aus Arbeitsrecht und Sozialrecht');
INSERT INTO course (name) VALUES ('030462 RE Repetitorium aus Arbeits- und Sozialrecht');
INSERT INTO course (name) VALUES ('030024 SE Seminar aus Arbeits- und Sportrecht');
INSERT INTO course (name) VALUES ('030074 SE Arbeitsrecht in der anwaltlichen Praxis');
INSERT INTO course (name) VALUES ('030093 SE Praxisseminar aus Arbeits- und Sozialrecht');
INSERT INTO course (name) VALUES ('030121 SE Praxisseminar aus Arbeits- und Sozialrecht');
INSERT INTO course (name) VALUES ('030357 SE Diplomand*innen Seminar - Schreibwerkstatt');
INSERT INTO course (name) VALUES ('030374 SE Seminar - Europäisches Arbeits- und Sozialrecht');
INSERT INTO course (name) VALUES ('030504 SE Seminar aus Arbeitsrecht und Rechtsgeschichte');
INSERT INTO course (name) VALUES ('030574 SE Judikatur-Seminar aus Arbeits- und Sozialrecht - Entgelt - Entgeltsicherung');
INSERT INTO course (name) VALUES ('030012 KU Arbeitsrechtliche Fälle aus anwaltlicher Perspektive');
INSERT INTO course (name) VALUES ('030071 KU Menschenrechtliche und europarechtliche Grundlagen von Gleichheit und Nichtdiskriminierung');
INSERT INTO course (name) VALUES ('030099 KU Zivilrechtliche Aspekte des Gleichbehandlungsrechts');
INSERT INTO course (name) VALUES ('030117 KU Equality/Diversity');
INSERT INTO course (name) VALUES ('030214 KU Praktische Rechtsdurchsetzung: Behörden und Verfahren - Prozessspiel');
INSERT INTO course (name) VALUES ('030234 KU European Labour and Social Security Law');
INSERT INTO course (name) VALUES ('030237 KU Behindertengleichstellung');
INSERT INTO course (name) VALUES ('030240 KU Diskriminierungsschutz - Implementierung, Bewusstsein und Argumentationstechnik');
INSERT INTO course (name) VALUES ('030304 KU Vertragsgestaltung im Arbeitsrecht');
INSERT INTO course (name) VALUES ('030476 KU Equality und Diversity in der betrieblichen Organisation');
INSERT INTO course (name) VALUES ('030160 VO Verfassungsgerichtsbarkeit/Europäische Gerichtsbarkeit');
INSERT INTO course (name) VALUES ('030267 VO Vorlesung: Verwaltungsrecht - Besonderer Teil');
INSERT INTO course (name) VALUES ('030337 VO Verfassungsrecht I (Staatslehre und Organisationsrecht)');
INSERT INTO course (name) VALUES ('030505 VO Verwaltungsverfahrensrecht einschließlich Verwaltungsgerichtsbarkeit');
INSERT INTO course (name) VALUES ('380006 VO Methodenlehre des öffentlichen Rechts');
INSERT INTO course (name) VALUES ('030139 UE Übung aus Verfassungsrecht');
INSERT INTO course (name) VALUES ('030346 UE Übung aus Verfassungsrecht');
INSERT INTO course (name) VALUES ('030363 UE Übung aus Verfassungsrecht');
INSERT INTO course (name) VALUES ('030408 UE Übung aus Verfassungsrecht');
INSERT INTO course (name) VALUES ('030446 UE Übung aus Verfassungsrecht');
INSERT INTO course (name) VALUES ('030019 UE Übung aus Öffentlichem Recht (FÜM III)');
INSERT INTO course (name) VALUES ('030173 UE Übung aus öffentlichem Recht (FÜM III)');
INSERT INTO course (name) VALUES ('030184 UE Übung aus öffentlichem Recht (FÜM III)');
INSERT INTO course (name) VALUES ('030202 UE Übung aus Öffentlichem Recht (FÜM III)');
INSERT INTO course (name) VALUES ('030328 UE Übung aus öffentlichem Recht (FÜM III)');
INSERT INTO course (name) VALUES ('030456 UE Übung aus öffentlichem Recht (FÜM III)');
INSERT INTO course (name) VALUES ('030355 KU Klausurenkurs aus öffentlichem Recht');
INSERT INTO course (name) VALUES ('030659 KO Konversatorium aus Verfassungsrecht');
INSERT INTO course (name) VALUES ('030061 SE Klimaschutz als Hype: the good, the bad or the ugly.');
INSERT INTO course (name) VALUES ('030062 SE Seminar aus öffentlichem Recht');
INSERT INTO course (name) VALUES ('030100 SE Seminar aus öffentlichem Recht');
INSERT INTO course (name) VALUES ('030163 SE Seminar aus öffentlichem Recht');
INSERT INTO course (name) VALUES ('030171 SE Seminar aus Öffentlichem Recht');
INSERT INTO course (name) VALUES ('030193 SE EU-Recht und staatliches Recht');
INSERT INTO course (name) VALUES ('030201 SE Seminar aus europäischem und österreichischem Finanzmarktaufsichtsrecht');
INSERT INTO course (name) VALUES ('030212 SE Seminar Klimaschutzrecht');
INSERT INTO course (name) VALUES ('030241 SE Innovation und legal tech regulation');
INSERT INTO course (name) VALUES ('030303 SE Blockchain rules. Der rechtliche Hintergrund von Blockchainanwendungen in Österreich und der EU');
INSERT INTO course (name) VALUES ('030342 SE Seminar aus Öffentlichem Recht: Aktuelle Rechtsprechung des Verfassungsgerichtshofes');
INSERT INTO course (name) VALUES ('030371 SE Coronabedingte Herausforderungen an Gewaltenteilung, Rechtsschutz und Demokratie');
INSERT INTO course (name) VALUES ('030424 SE Die Grenzen der juristischen Auslegung am Beispiel der Coronakrise');
INSERT INTO course (name) VALUES ('030461 SE Aktuelle Fragen des verfassungsrechtlichen Eigentumsschutzes');
INSERT INTO course (name) VALUES ('030464 SE Algorithmen der Verwaltung');
INSERT INTO course (name) VALUES ('030500 SE Ausgewählte Fragen des vergleichenden Verfassungsrechts');
INSERT INTO course (name) VALUES ('030665 SE Seminar aus öffentlichem Recht (Verfassungsrecht: Grund- und Menschenrechte)');
INSERT INTO course (name) VALUES ('030039 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030210 KU Folgt das Recht der Politik?');
INSERT INTO course (name) VALUES ('030338 KU Aktuelle Rechtsprechung des Verfassungsgerichtshofs in vergeichender Perspektive:');
INSERT INTO course (name) VALUES ('030349 KU Comparative Constitutional Law in Post-Conflict Settings');
INSERT INTO course (name) VALUES ('030435 KU Verfahrensrecht in der Rechtsprechung des Verwaltungsgerichtshofes');
INSERT INTO course (name) VALUES ('030451 KU Privatsphäre im Überwachungszeitalter');
INSERT INTO course (name) VALUES ('030474 KU Verfassungsrecht verstehen');
INSERT INTO course (name) VALUES ('030535 KU Parlamentarismus im Spannungsverhältnis von Verfassung, Geschäftsordnung und Parlamentspraxis');
INSERT INTO course (name) VALUES ('030541 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030625 KU Kurs aus Verfassungsrecht');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030160 VO Verfassungsgerichtsbarkeit/Europäische Gerichtsbarkeit');
INSERT INTO course (name) VALUES ('030177 VO Europäisches Wettbewerbsrecht');
INSERT INTO course (name) VALUES ('030515 VO Rechtsschutz im Unionsrecht');
INSERT INTO course (name) VALUES ('030591 VO Grundfreiheiten und Binnenmarkt');
INSERT INTO course (name) VALUES ('030427 UE Übung aus Europarecht');
INSERT INTO course (name) VALUES ('030483 UE Übung aus Europarecht, Schwerpunktübung');
INSERT INTO course (name) VALUES ('030495 UE Practical exercises in EU-Law');
INSERT INTO course (name) VALUES ('030234 KU European Labour and Social Security Law');
INSERT INTO course (name) VALUES ('030415 KU Europäisches Vergaberecht');
INSERT INTO course (name) VALUES ('030526 KU EU Judicature');
INSERT INTO course (name) VALUES ('030600 KU Introduction to European Union Law');
INSERT INTO course (name) VALUES ('030308 SE Seminar Europäisches Binnenmarkt- und Wettbewerbsrecht');
INSERT INTO course (name) VALUES ('030309 SE European Union Law Seminar');
INSERT INTO course (name) VALUES ('030368 SE Seminar aus Europarecht- Covid-19: Pandemiebekämpfung zwischen Krisenmanagement und Solidarität');
INSERT INTO course (name) VALUES ('030423 SE Seminar aus Rechtsinformatik');
INSERT INTO course (name) VALUES ('030603 SE Seminar aus Europarecht');
INSERT INTO course (name) VALUES ('030472 MC European Law Moot Court Competition');
INSERT INTO course (name) VALUES ('030025 VO Völkerrecht I');
INSERT INTO course (name) VALUES ('030172 UE Übung aus Völkerrecht');
INSERT INTO course (name) VALUES ('030482 UE Übung aus Völkerrecht');
INSERT INTO course (name) VALUES ('030506 UE Übung aus Völkerrecht');
INSERT INTO course (name) VALUES ('030154 RE Repetitorium aus Völkerrecht');
INSERT INTO course (name) VALUES ('030055 SE Seminar aus Völkerrecht: Völkerrechtliches Verfahrensrecht');
INSERT INTO course (name) VALUES ('030119 SE Advanced Research Seminar: Responsibility in International Law');
INSERT INTO course (name) VALUES ('030238 SE Seminar aus Völkerrecht: Internationale Organisationen und die Corona Pandemie');
INSERT INTO course (name) VALUES ('030326 SE Comparative Emergency Measures against the Pandemic');
INSERT INTO course (name) VALUES ('030423 SE Seminar aus Rechtsinformatik');
INSERT INTO course (name) VALUES ('030570 SE Seminar aus Völkerrecht: Pandemien im Völkerrecht');
INSERT INTO course (name) VALUES ('030090 MC Jessup Moot Court, International Law Moot Court');
INSERT INTO course (name) VALUES ('030379 MC Manfred Lachs Space Law Moot Court');
INSERT INTO course (name) VALUES ('030606 MC International Investment Arbitration Moot Court');
INSERT INTO course (name) VALUES ('030414 VO Steuerrecht');
INSERT INTO course (name) VALUES ('030586 VO Aktuelle Fragen zur Unternehmensbesteuerung');
INSERT INTO course (name) VALUES ('030235 UE Übung aus Steuerrecht');
INSERT INTO course (name) VALUES ('030389 UE Übung aus Steuerrecht');
INSERT INTO course (name) VALUES ('030399 UE Übung aus Steuerrecht');
INSERT INTO course (name) VALUES ('030551 UE Übung aus Steuerrecht');
INSERT INTO course (name) VALUES ('030576 UE Übung aus Steuerrecht');
INSERT INTO course (name) VALUES ('030634 UE Übung aus Steuerrecht');
INSERT INTO course (name) VALUES ('030146 VO Repetitorium aus Finanzrecht/Steuerrecht');
INSERT INTO course (name) VALUES ('030430 SE Seminar aus Finanzrecht/Steuerrecht');
INSERT INTO course (name) VALUES ('030615 SE Seminar aus Finanzrecht/Steuerrecht');
INSERT INTO course (name) VALUES ('030417 VO Juristische Wirtschaftskompetenz');
INSERT INTO course (name) VALUES ('030397 KU Crashkurs BAO/FinStrG');
INSERT INTO course (name) VALUES ('030559 KU Globalisierung und Rechtspluralismus');
INSERT INTO course (name) VALUES ('030560 SE Fritz Bauer oder: Auschwitz vor Gericht');
INSERT INTO course (name) VALUES ('030015 SE Spinozas Rechtsdenken zwischen Religion und Staat');
INSERT INTO course (name) VALUES ('030246 SE Dimensionen des Politischen: Demokratie im Ausnahmezustand');
INSERT INTO course (name) VALUES ('030300 SE Seminar aus Rechtsphilosophie: Zur Theorie von Strafe und Strafrecht');
INSERT INTO course (name) VALUES ('030352 SE Tragödie im Recht, Tragödie des Rechts');
INSERT INTO course (name) VALUES ('030401 KU Spinozas Rechtsethik zwischen Sicherheit und Freiheit');
INSERT INTO course (name) VALUES ('030426 KU Politische Philosophie und Philosophie des Rechts');
INSERT INTO course (name) VALUES ('030502 KU An Introduction to Legal Theory');
INSERT INTO course (name) VALUES ('030580 KU Private Law Theory');
INSERT INTO course (name) VALUES ('380001 VO Juristische Methodenlehre');
INSERT INTO course (name) VALUES ('030287 SE Law and Literature: Margaret Atwood, Der Report der Magd (1985) und Die Zeuginnen (2019)');
INSERT INTO course (name) VALUES ('030371 SE Coronabedingte Herausforderungen an Gewaltenteilung, Rechtsschutz und Demokratie');
INSERT INTO course (name) VALUES ('030425 SE Seminar aus Rechtsphilosophie und Religionsrecht: Menschenrechte - Frauenrechte');
INSERT INTO course (name) VALUES ('030038 KU Geschichte des österreichischen Justizrechts - Geltung und Ausstrahlung nach 1918');
INSERT INTO course (name) VALUES ('030054 VO Juden und Judenheit(en) in Österreich. Eine Rechtsgeschichte.');
INSERT INTO course (name) VALUES ('030141 KU Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030191 KU Kurs gegenchronologische Verfassungsgeschichte 20. Jhdt.');
INSERT INTO course (name) VALUES ('030194 KU Islam in Europa');
INSERT INTO course (name) VALUES ('030269 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030272 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030285 VO Ringvorlesung "Antike Rechtsgeschichte"');
INSERT INTO course (name) VALUES ('030373 VO Aus der Werkstatt: Aktuelle rechtshistorische Forschungen am Juridicum');
INSERT INTO course (name) VALUES ('030589 KU Handschriften und Quellen - Jüdische Sprachen (Hebräisch, Judendeutsch und Jiddisch)');
INSERT INTO course (name) VALUES ('030613 KU Geschichte des Strafrechts und des Strafverfahrensrechts');
INSERT INTO course (name) VALUES ('030621 KU Handschriften und Quellen, Deutsch und Latein');
INSERT INTO course (name) VALUES ('030664 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030673 KU Berühmte kirchliche Prozesse des Mittelalters');
INSERT INTO course (name) VALUES ('030078 SE Seminar: Rechtsgeschichte der Wirtschaft');
INSERT INTO course (name) VALUES ('030197 SE Geschichte des Medizinrechts');
INSERT INTO course (name) VALUES ('030256 SE Seminar aus europäischer und vergleichender Rechtsgeschichte für Diplomand*innen u. Dissertant*innen');
INSERT INTO course (name) VALUES ('030274 SE "Judentümer"- Rechts-, Politik-, Sozial- und Kulturgeschichte der Juden in der Neuzeit');
INSERT INTO course (name) VALUES ('030299 KU Rechtsgeschichte des vormodernen Europa');
INSERT INTO course (name) VALUES ('030311 VO Frauen im Recht (Teil B): Frauen in den Rechtsberufen - Rechtsgeschichte');
INSERT INTO course (name) VALUES ('030393 SE Seminar aus Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030418 SE Seminar: Große Prozesse');
INSERT INTO course (name) VALUES ('030420 VO Geschichte der Grund- und Menschenrechte');
INSERT INTO course (name) VALUES ('030528 SE Seminar: Normsetzung und Rechtsprechung im Nationalsozialismus. Ausgewählte Aspekte');
INSERT INTO course (name) VALUES ('030557 SE Die Ausgestaltung des Religionsunterrichts und des Ethikunterrichts');
INSERT INTO course (name) VALUES ('030566 MC Ius Commune Moot Court');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030655 VO Introduction to Islamic Law');
INSERT INTO course (name) VALUES ('030667 KU Introduction to Jewish Law in Context: Legal Sources, Time &amp; Space');
INSERT INTO course (name) VALUES ('030684 SE SE ohne Generalthema');
INSERT INTO course (name) VALUES ('030707 SE Seminar aus Rechts- und Verfassungsgeschichte: Rechtspolitische Filme der Zwischenkriegszeit');
INSERT INTO course (name) VALUES ('030041 VO Römische Rechtsgeschichte und ausgewählte Gebiete des Personen- und Familienrechts');
INSERT INTO course (name) VALUES ('030102 KU Gleichberechtigung zwischen Frauen und Männern');
INSERT INTO course (name) VALUES ('030269 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030272 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030370 KU Il Diritto Pubblico di Roma dalla Monarchia alla Repubblica (VIII-I sec. a.C.)');
INSERT INTO course (name) VALUES ('030392 KU Die römische Gesellschaft');
INSERT INTO course (name) VALUES ('030524 SE Aktuelle Forschungen im Bereich des Röm. Rechts u. seiner Fortwirkung in den geltenden Privatrechten');
INSERT INTO course (name) VALUES ('030549 SE Seminar aus Römischem Recht - Kaufen wie in Troja');
INSERT INTO course (name) VALUES ('030664 KU Digestenexegese');
INSERT INTO course (name) VALUES ('030026 KU Rechtsfragen von Lebensgemeinschaften und Lebenspartnerschaften');
INSERT INTO course (name) VALUES ('030102 KU Gleichberechtigung zwischen Frauen und Männern');
INSERT INTO course (name) VALUES ('030311 VO Frauen im Recht (Teil B): Frauen in den Rechtsberufen - Rechtsgeschichte');
INSERT INTO course (name) VALUES ('030056 KU Österreichische und internationale Judikatur zu Gender und anderen Diskriminierungsgründen');
INSERT INTO course (name) VALUES ('030246 SE Dimensionen des Politischen: Demokratie im Ausnahmezustand');
INSERT INTO course (name) VALUES ('030316 KU Women in Law (Part A): Women in Legal Professions - Contemporary Issues');
INSERT INTO course (name) VALUES ('030375 KU Gender-Probleme in der familien- und scheidungsrechtlichen Praxis');
INSERT INTO course (name) VALUES ('030393 SE Seminar aus Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030425 SE Seminar aus Rechtsphilosophie und Religionsrecht: Menschenrechte - Frauenrechte');
INSERT INTO course (name) VALUES ('240097 VO VM7 - Eine von fünf');
INSERT INTO course (name) VALUES ('030050 KU Einführung in empirisches Arbeiten');
INSERT INTO course (name) VALUES ('030077 VO Strafvollzug');
INSERT INTO course (name) VALUES ('030265 KU Aktuelle Kriminalpolitik');
INSERT INTO course (name) VALUES ('030468 VO Vernehmungs- und Spurenkunde');
INSERT INTO course (name) VALUES ('030013 KU Strafverteidigung in der Praxis');
INSERT INTO course (name) VALUES ('030049 KU IT-Strafrecht I');
INSERT INTO course (name) VALUES ('030050 KU Einführung in empirisches Arbeiten');
INSERT INTO course (name) VALUES ('030107 KU Strafrechtliche Haftung der Heilberufe');
INSERT INTO course (name) VALUES ('030108 VO Die Behandlung zurechnungsunfähiger geistig abnormer Rechtsbrecher');
INSERT INTO course (name) VALUES ('030129 KU International Criminal Law and its Enforcement');
INSERT INTO course (name) VALUES ('030135 KU Schriftvergleichung und Urkundenuntersuchung');
INSERT INTO course (name) VALUES ('030138 SE Seminar aus Finanzstrafrecht: Tax and Crime');
INSERT INTO course (name) VALUES ('030147 SE Seminar aus Kriminologie und Strafrecht');
INSERT INTO course (name) VALUES ('030169 KU Privatissimum aus Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030199 KU Course: "European Criminal Law"');
INSERT INTO course (name) VALUES ('030215 KU Drogenkriminalität in Theorie und Praxis');
INSERT INTO course (name) VALUES ('030226 SE Seminar "Korruption und Amtsmissbrauch"');
INSERT INTO course (name) VALUES ('030287 SE Law and Literature: Margaret Atwood, Der Report der Magd (1985) und Die Zeuginnen (2019)');
INSERT INTO course (name) VALUES ('030300 SE Seminar aus Rechtsphilosophie: Zur Theorie von Strafe und Strafrecht');
INSERT INTO course (name) VALUES ('030305 KU Wirtschaftsstrafrecht in der Praxis');
INSERT INTO course (name) VALUES ('030324 SE Aktuelle Fragen zum Strafprozessrecht');
INSERT INTO course (name) VALUES ('030325 KU Hasskriminalität im österreichischen und internationalen Kontext');
INSERT INTO course (name) VALUES ('030336 SE Interkulturelles Strafrecht');
INSERT INTO course (name) VALUES ('030361 SE Strafrechtliche Grenzen investigativen Journalismus');
INSERT INTO course (name) VALUES ('030369 VO Gerichtliche Medizin für Juristen I (von II)');
INSERT INTO course (name) VALUES ('030378 KU Justiz und Rechtsstaatlichkeit');
INSERT INTO course (name) VALUES ('030384 KU White-Collar Crime, Compliance &amp; Investigations');
INSERT INTO course (name) VALUES ('030463 KU Legal Literacy: Recht einfach präsentieren');
INSERT INTO course (name) VALUES ('030478 KU Gerichts-Praxis: Die Tätigkeit der Richter*innen und Staatsanwält*innen');
INSERT INTO course (name) VALUES ('030490 SE Undercover: Geheime Ermittlungsmaßnahmen im Strafprozess');
INSERT INTO course (name) VALUES ('030501 SE Seminar zur Ausstellung "Kunst und Strafrecht"');
INSERT INTO course (name) VALUES ('030503 SE Grenzüberschreitende Organisierte Kriminalität: Illegaler Waffen- und Kriegsmaterialhandel');
INSERT INTO course (name) VALUES ('030544 KU Jugendstrafrecht und Strafvollzug');
INSERT INTO course (name) VALUES ('030553 KU Änderungsbedarf in der Strafverfolgungs- und Strafverfahrenspraxis in Österreich?');
INSERT INTO course (name) VALUES ('030611 SE Seminar aus Strafrecht und Strafprozessrecht');
INSERT INTO course (name) VALUES ('030613 KU Geschichte des Strafrechts und des Strafverfahrensrechts');
INSERT INTO course (name) VALUES ('030622 VO Evolution und biologische Grundlagen menschlichen Verhaltens');
INSERT INTO course (name) VALUES ('030070 KU Immobiliensteuerrecht');
INSERT INTO course (name) VALUES ('030450 KU Wohnungseigentumsrecht');
INSERT INTO course (name) VALUES ('030064 KU Grundbuchsrecht und Liegenschaftsverträge in der Praxis');
INSERT INTO course (name) VALUES ('030521 KU Steuerliche Aspekte bei Liegenschaftstransaktionen');
INSERT INTO course (name) VALUES ('030026 KU Rechtsfragen von Lebensgemeinschaften und Lebenspartnerschaften');
INSERT INTO course (name) VALUES ('030095 SE Seminar aus Zivilrecht');
INSERT INTO course (name) VALUES ('030115 KU Das neue Erwachsenenschutzrecht');
INSERT INTO course (name) VALUES ('030220 KU Europäisches Familienrecht mit Fokus auf Internationales Kinder- und Erwachsenenschutzrecht');
INSERT INTO course (name) VALUES ('030321 KU Internationales Familienrecht');
INSERT INTO course (name) VALUES ('030353 KU Erbrecht und Familie');
INSERT INTO course (name) VALUES ('030548 KU Bis Richter oder Tod Euch scheiden');
INSERT INTO course (name) VALUES ('030602 PR Testamente-Werkstatt');
INSERT INTO course (name) VALUES ('240097 VO VM7 - Eine von fünf');
INSERT INTO course (name) VALUES ('030196 KU Wettbewerbsrecht (UWG)');
INSERT INTO course (name) VALUES ('030204 KU Verbraucherrecht');
INSERT INTO course (name) VALUES ('030249 KU Europäisches und österreichisches Kartellrecht');
INSERT INTO course (name) VALUES ('030290 VO Geistiges Eigentum');
INSERT INTO course (name) VALUES ('030444 KU Vereins- und Stiftungsrecht');
INSERT INTO course (name) VALUES ('030445 KU Rechnungslegungsrecht');
INSERT INTO course (name) VALUES ('030681 KU M &amp; A International Part I (Corporate Law)');
INSERT INTO course (name) VALUES ('030005 SE Moot Court aus International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030045 KU Materielles Insolvenzrecht mit Schwerpunkt Anfechtungsrecht');
INSERT INTO course (name) VALUES ('030079 KU Praktische Vertragsgestaltung im Unternehmens-und Gesellschaftsrecht II');
INSERT INTO course (name) VALUES ('030151 KU Übernahmerecht');
INSERT INTO course (name) VALUES ('030157 KU Kartellrecht für Fortgeschrittene');
INSERT INTO course (name) VALUES ('030192 KU Corporate Governance bei börsennotierten Aktiengesellschaften');
INSERT INTO course (name) VALUES ('030384 KU White-Collar Crime, Compliance &amp; Investigations');
INSERT INTO course (name) VALUES ('030403 VO International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030455 KU CISG at 40 - Course on Transnational Commercial Law (in cooperation with UNCITRAL)');
INSERT INTO course (name) VALUES ('030478 KU Gerichts-Praxis: Die Tätigkeit der Richter*innen und Staatsanwält*innen');
INSERT INTO course (name) VALUES ('030481 KU Startup Clinic');
INSERT INTO course (name) VALUES ('030631 VO Internationales Unternehmensrecht');
INSERT INTO course (name) VALUES ('030737 KU Case studies: Mergers &amp; Acquisitions');
INSERT INTO course (name) VALUES ('030039 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030166 SE Aktuelle Entwicklungen im Internationalen Privat- und Verfahrensrecht');
INSERT INTO course (name) VALUES ('030174 KU Comparative Private International Law');
INSERT INTO course (name) VALUES ('030206 KU Einführung in das Schadenersatzrecht');
INSERT INTO course (name) VALUES ('030220 KU Europäisches Familienrecht mit Fokus auf Internationales Kinder- und Erwachsenenschutzrecht');
INSERT INTO course (name) VALUES ('030228 KU Einführung in das österreichische Sportrecht');
INSERT INTO course (name) VALUES ('030233 KU Legal Writing');
INSERT INTO course (name) VALUES ('030251 KU Introduction to Japanese Law');
INSERT INTO course (name) VALUES ('030262 KU International Legal English I');
INSERT INTO course (name) VALUES ('030277 KU Introducción al derecho espanol y terminología jurídica espanola');
INSERT INTO course (name) VALUES ('030297 KU Public Markets, Securities Regulation and Corporate Governance');
INSERT INTO course (name) VALUES ('030307 KU Internationales Vertragsrecht und vereinheitlichtes Kaufrecht');
INSERT INTO course (name) VALUES ('030317 KU Laws of Armed Conflict');
INSERT INTO course (name) VALUES ('030321 KU Internationales Familienrecht');
INSERT INTO course (name) VALUES ('030326 SE Comparative Emergency Measures against the Pandemic');
INSERT INTO course (name) VALUES ('030367 KU Juristische Recherche im grenzüberschreitenden Kontext');
INSERT INTO course (name) VALUES ('030385 KU Drafting and Negotiating Cross-border M &amp; A and Joint Venture Contracts');
INSERT INTO course (name) VALUES ('030390 KU Einführung in Rechtsordnungen der ehemaligen sozialistischen Länder');
INSERT INTO course (name) VALUES ('030403 VO International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030509 SE Seminar aus Zivilrecht und IPR / Civilno pravo in mednarodno zasebno pravo');
INSERT INTO course (name) VALUES ('030530 KU Rechtsvergleichung');
INSERT INTO course (name) VALUES ('030533 KU International Business Transactions');
INSERT INTO course (name) VALUES ('030534 SE COVID-19 and International Dispute Resolution');
INSERT INTO course (name) VALUES ('030536 KU Das System des Europäischen Unionsrechts');
INSERT INTO course (name) VALUES ('030541 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030561 KU International Legal English II');
INSERT INTO course (name) VALUES ('030562 KU Direkt aus Brüssel: Aktuelle Fragen des Europarechts');
INSERT INTO course (name) VALUES ('030563 KU International Legal English II');
INSERT INTO course (name) VALUES ('030568 KU Discussion, Negotiation and Presentation in English');
INSERT INTO course (name) VALUES ('030594 KU International Legal English I');
INSERT INTO course (name) VALUES ('030619 KU International Legal English I');
INSERT INTO course (name) VALUES ('030631 VO Internationales Unternehmensrecht');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030654 KU Emergency Laws in Comparative Perspective');
INSERT INTO course (name) VALUES ('030655 VO Introduction to Islamic Law');
INSERT INTO course (name) VALUES ('030033 KU Rechtliche Aspekte der außergerichtlichen Konfliktregelung insbesondere Mediation und Schlichtung');
INSERT INTO course (name) VALUES ('030428 KU Grundlagen der alternativen Konfliktregelung');
INSERT INTO course (name) VALUES ('030433 KU Kommunikation in der Konfliktregelung');
INSERT INTO course (name) VALUES ('030572 KU Konfliktanalyse in der außergerichtlichen Streitbeilegung');
INSERT INTO course (name) VALUES ('030006 KU Introduction to Negotiation');
INSERT INTO course (name) VALUES ('030016 KU Prozesstaktik - Entscheidung zwischen Mediation und Streit');
INSERT INTO course (name) VALUES ('030124 MC ICC International Commercial Mediation Moot Court');
INSERT INTO course (name) VALUES ('030155 KU Mediation im Bau- und Immobilienbereich');
INSERT INTO course (name) VALUES ('030198 KU Mediation for Lawyers');
INSERT INTO course (name) VALUES ('030334 KU Mediation im transkulturellen Kontext');
INSERT INTO course (name) VALUES ('030437 KU Angewandte Mediation');
INSERT INTO course (name) VALUES ('030449 KU Collaborative Law und konsensorientiertes Verhandeln - Aspekte der interprofessionellen Teamarbeit');
INSERT INTO course (name) VALUES ('030542 KU Verhandeln für Jurist*innen vor Gericht');
INSERT INTO course (name) VALUES ('030092 VO Versicherungsvertragsrecht, Allgemeiner Teil');
INSERT INTO course (name) VALUES ('030698 KU Grundzüge der Schadensversicherung');
INSERT INTO course (name) VALUES ('030008 KU Grundzüge des Versicherungsaufsichtsrechts');
INSERT INTO course (name) VALUES ('030045 KU Materielles Insolvenzrecht mit Schwerpunkt Anfechtungsrecht');
INSERT INTO course (name) VALUES ('030151 KU Übernahmerecht');
INSERT INTO course (name) VALUES ('030201 SE Seminar aus europäischem und österreichischem Finanzmarktaufsichtsrecht');
INSERT INTO course (name) VALUES ('030289 KU Allgemeine vertragsrechtliche Probleme, dargestellt an Beispielen aus dem Vertragsversicherungsrecht');
INSERT INTO course (name) VALUES ('030436 SE Seminar aus Zivilverfahrensrecht: Schwerpunkt: Insolvenz- und Restrukturierungsrecht');
INSERT INTO course (name) VALUES ('030048 KU E-Commerce');
INSERT INTO course (name) VALUES ('030049 KU IT-Strafrecht I');
INSERT INTO course (name) VALUES ('030057 KU E-Government');
INSERT INTO course (name) VALUES ('030350 KU Elektronische Zahlung, Bankgeschäfte und Wertpapierhandel');
INSERT INTO course (name) VALUES ('030372 KU Urheberrecht und elektronische Medien');
INSERT INTO course (name) VALUES ('030142 KU Legal Informatics');
INSERT INTO course (name) VALUES ('030223 KU Persönlichkeitsrechte');
INSERT INTO course (name) VALUES ('030250 SE Seminar: Aktuelle Fragen des IT-Rechts für Diplomand*innen');
INSERT INTO course (name) VALUES ('030258 KU Programmieren für Jurist*innen');
INSERT INTO course (name) VALUES ('030278 KU Vertragsrecht, AGB-Kontrolle und Netzneutralität im Telekom-Bereich');
INSERT INTO course (name) VALUES ('030359 KU Internet of Things and Human Rights');
INSERT INTO course (name) VALUES ('030362 KU Distributed Ledger Technologies Beyond Financial Applications');
INSERT INTO course (name) VALUES ('030366 SE Seminar aus Internetrecht');
INSERT INTO course (name) VALUES ('030423 SE Seminar aus Rechtsinformatik');
INSERT INTO course (name) VALUES ('030438 KU Introduction into European IT-Law');
INSERT INTO course (name) VALUES ('030522 KU Aktuelle rechtliche Fragen zu Innovation und Digitalisierung');
INSERT INTO course (name) VALUES ('030531 KU Datenschutz im Arbeitsverhältnis');
INSERT INTO course (name) VALUES ('030587 KU Softwarerecht');
INSERT INTO course (name) VALUES ('030597 KU Künstliche Intelligenz und Recht');
INSERT INTO course (name) VALUES ('490400 VU PM1 Digitale Transformationen');
INSERT INTO course (name) VALUES ('030012 KU Arbeitsrechtliche Fälle aus anwaltlicher Perspektive');
INSERT INTO course (name) VALUES ('030304 KU Vertragsgestaltung im Arbeitsrecht');
INSERT INTO course (name) VALUES ('030697 KU Vertragsgestaltung I');
INSERT INTO course (name) VALUES ('030737 KU Case studies: Mergers &amp; Acquisitions');
INSERT INTO course (name) VALUES ('030249 KU Europäisches und österreichisches Kartellrecht');
INSERT INTO course (name) VALUES ('030526 KU EU Judicature');
INSERT INTO course (name) VALUES ('030536 KU Das System des Europäischen Unionsrechts');
INSERT INTO course (name) VALUES ('030030 KU Die europäischen Grundfreiheiten in der Fallbearbeitung - Übungen anhand aktueller Klausurbeispiele');
INSERT INTO course (name) VALUES ('030036 KU European Competition Procedures');
INSERT INTO course (name) VALUES ('030039 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030102 KU Gleichberechtigung zwischen Frauen und Männern');
INSERT INTO course (name) VALUES ('030157 KU Kartellrecht für Fortgeschrittene');
INSERT INTO course (name) VALUES ('030193 SE EU-Recht und staatliches Recht');
INSERT INTO course (name) VALUES ('030220 KU Europäisches Familienrecht mit Fokus auf Internationales Kinder- und Erwachsenenschutzrecht');
INSERT INTO course (name) VALUES ('030225 KU Der Europäische Gerichtshof - Organisation und aktuelle Rechtsprechung');
INSERT INTO course (name) VALUES ('030230 KU Der Raum der Freiheit, der Sicherheit und des Rechts der EU');
INSERT INTO course (name) VALUES ('030234 KU European Labour and Social Security Law');
INSERT INTO course (name) VALUES ('030239 SE European and International Business and Technology Law Seminar');
INSERT INTO course (name) VALUES ('030243 SE EU Asyl- und Migrationsrecht: Ausgewählte Problemfelder und Perspektiven');
INSERT INTO course (name) VALUES ('030244 VO European Union Internal Market Law');
INSERT INTO course (name) VALUES ('030308 SE Seminar Europäisches Binnenmarkt- und Wettbewerbsrecht');
INSERT INTO course (name) VALUES ('030309 SE European Union Law Seminar');
INSERT INTO course (name) VALUES ('030327 KU EU Internal Market and Public Procurement Law');
INSERT INTO course (name) VALUES ('030332 SE Grundlagen der Rechtsethik I');
INSERT INTO course (name) VALUES ('030368 SE Seminar aus Europarecht- Covid-19: Pandemiebekämpfung zwischen Krisenmanagement und Solidarität');
INSERT INTO course (name) VALUES ('030371 SE Coronabedingte Herausforderungen an Gewaltenteilung, Rechtsschutz und Demokratie');
INSERT INTO course (name) VALUES ('030374 SE Seminar - Europäisches Arbeits- und Sozialrecht');
INSERT INTO course (name) VALUES ('030390 KU Einführung in Rechtsordnungen der ehemaligen sozialistischen Länder');
INSERT INTO course (name) VALUES ('030410 KU Europäische Wettbewerbspolitik');
INSERT INTO course (name) VALUES ('030415 KU Europäisches Vergaberecht');
INSERT INTO course (name) VALUES ('030416 SE Europäisches Umweltrecht: Klimaschutz und Energie');
INSERT INTO course (name) VALUES ('030423 SE Seminar aus Rechtsinformatik');
INSERT INTO course (name) VALUES ('030459 KU The Constitutional Foundations of Substantive EU Law');
INSERT INTO course (name) VALUES ('030472 MC European Law Moot Court Competition');
INSERT INTO course (name) VALUES ('030541 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030562 KU Direkt aus Brüssel: Aktuelle Fragen des Europarechts');
INSERT INTO course (name) VALUES ('030600 KU Introduction to European Union Law');
INSERT INTO course (name) VALUES ('030601 KU Free Movement of Persons in European Union Law');
INSERT INTO course (name) VALUES ('030603 SE Seminar aus Europarecht');
INSERT INTO course (name) VALUES ('030652 KU EU Constitutional Law: The Evolving Constitution of the European Union');
INSERT INTO course (name) VALUES ('030681 KU M &amp; A International Part I (Corporate Law)');
INSERT INTO course (name) VALUES ('040199 VO EC BW: Quantitative betriebswirtschaftliche Methoden');
INSERT INTO course (name) VALUES ('040576 VO StEOP: Grundzüge der Statistik');
INSERT INTO course (name) VALUES ('040002 VO ABWL Finanzwirtschaft I');
INSERT INTO course (name) VALUES ('040022 VO Buchhaltung');
INSERT INTO course (name) VALUES ('040038 VO Kostenrechnung');
INSERT INTO course (name) VALUES ('040058 VO ABWL Unternehmensführung I');
INSERT INTO course (name) VALUES ('040119 VO ABWL Marketing I');
INSERT INTO course (name) VALUES ('040136 VO ABWL Produktion und Logistik I');
INSERT INTO course (name) VALUES ('040628 VO Bilanzierung');
INSERT INTO course (name) VALUES ('040002 VO ABWL Finanzwirtschaft I');
INSERT INTO course (name) VALUES ('040022 VO Buchhaltung');
INSERT INTO course (name) VALUES ('040038 VO Kostenrechnung');
INSERT INTO course (name) VALUES ('040058 VO ABWL Unternehmensführung I');
INSERT INTO course (name) VALUES ('040119 VO ABWL Marketing I');
INSERT INTO course (name) VALUES ('040136 VO ABWL Produktion und Logistik I');
INSERT INTO course (name) VALUES ('040628 VO Bilanzierung');
INSERT INTO course (name) VALUES ('030034 KU Medizinrecht I');
INSERT INTO course (name) VALUES ('030107 KU Strafrechtliche Haftung der Heilberufe');
INSERT INTO course (name) VALUES ('030405 KU Erbringung medizinischer Dienstleistungen im Krankenhaus');
INSERT INTO course (name) VALUES ('020052 KU Clinical Rounds');
INSERT INTO course (name) VALUES ('030060 VO Patentrecht I');
INSERT INTO course (name) VALUES ('030068 KU Privatissimum Medizinrecht');
INSERT INTO course (name) VALUES ('030088 KU Arzneimittel- und Apothekenrecht');
INSERT INTO course (name) VALUES ('030197 SE Geschichte des Medizinrechts');
INSERT INTO course (name) VALUES ('030292 VO Gentechnikrecht');
INSERT INTO course (name) VALUES ('030380 KU Ärztliches Berufsrecht');
INSERT INTO course (name) VALUES ('030406 SE Seminar aus Medizinrecht');
INSERT INTO course (name) VALUES ('030429 KU Medizinrecht in Film &amp; Debatte');
INSERT INTO course (name) VALUES ('030571 SE Seminar aus Medizinrecht');
INSERT INTO course (name) VALUES ('030618 KU Umweltrecht');
INSERT INTO course (name) VALUES ('030076 KU Produktbezogenes Umweltrecht, Chemikalienrecht');
INSERT INTO course (name) VALUES ('030165 KU Kurs aus österreichischem und europäischem Tierschutzrecht');
INSERT INTO course (name) VALUES ('030212 SE Seminar Klimaschutzrecht');
INSERT INTO course (name) VALUES ('030301 KU Einführung in das Abfallwirtschaftsrecht');
INSERT INTO course (name) VALUES ('030341 KU Praxis der Energiemarktregulierung');
INSERT INTO course (name) VALUES ('030431 KU Das Recht der Genehmigungsverfahren bei Infrastrukturvorhaben');
INSERT INTO course (name) VALUES ('030443 KU Wasserrecht');
INSERT INTO course (name) VALUES ('030134 KU Wirtschaftsrecht II');
INSERT INTO course (name) VALUES ('030185 KU Wirtschaftsrecht I');
INSERT INTO course (name) VALUES ('030008 KU Grundzüge des Versicherungsaufsichtsrechts');
INSERT INTO course (name) VALUES ('030122 KU Europäisches und Österreichisches Vergaberecht');
INSERT INTO course (name) VALUES ('030201 SE Seminar aus europäischem und österreichischem Finanzmarktaufsichtsrecht');
INSERT INTO course (name) VALUES ('030303 SE Blockchain rules. Der rechtliche Hintergrund von Blockchainanwendungen in Österreich und der EU');
INSERT INTO course (name) VALUES ('030339 KU Fernseh- und Radiorecht');
INSERT INTO course (name) VALUES ('030341 KU Praxis der Energiemarktregulierung');
INSERT INTO course (name) VALUES ('030431 KU Das Recht der Genehmigungsverfahren bei Infrastrukturvorhaben');
INSERT INTO course (name) VALUES ('030448 KU eSport-Recht');
INSERT INTO course (name) VALUES ('030461 SE Aktuelle Fragen des verfassungsrechtlichen Eigentumsschutzes');
INSERT INTO course (name) VALUES ('030543 KU Regulierung elektronischer Kommunikationsnetze und -dienste');
INSERT INTO course (name) VALUES ('030229 KU International Human Rights Law');
INSERT INTO course (name) VALUES ('030644 KU Grundrechtstheorie und Grundrechtsdogmatik in der Rechtsprechung');
INSERT INTO course (name) VALUES ('030053 KU Politische Grundrechte');
INSERT INTO course (name) VALUES ('030072 KU Religions- und Weltanschauungsfreiheit in Österreich');
INSERT INTO course (name) VALUES ('030109 KU Human Rights II  (F)');
INSERT INTO course (name) VALUES ('030163 SE Seminar aus öffentlichem Recht');
INSERT INTO course (name) VALUES ('030194 KU Islam in Europa');
INSERT INTO course (name) VALUES ('030271 PR Praktikum: Österreichischer Grundrechtsschutz in der Praxis');
INSERT INTO course (name) VALUES ('030371 SE Coronabedingte Herausforderungen an Gewaltenteilung, Rechtsschutz und Demokratie');
INSERT INTO course (name) VALUES ('030420 VO Geschichte der Grund- und Menschenrechte');
INSERT INTO course (name) VALUES ('030425 SE Seminar aus Rechtsphilosophie und Religionsrecht: Menschenrechte - Frauenrechte');
INSERT INTO course (name) VALUES ('030432 SE Grundrechtsschutz und Rechtsstaatlichkeit in Krisenzeiten');
INSERT INTO course (name) VALUES ('030441 SE Wie streitbar soll und darf eine Demokratie in der Verteidigung ihrer Fundamente u. Grundwerte sein?');
INSERT INTO course (name) VALUES ('030451 KU Privatsphäre im Überwachungszeitalter');
INSERT INTO course (name) VALUES ('030461 SE Aktuelle Fragen des verfassungsrechtlichen Eigentumsschutzes');
INSERT INTO course (name) VALUES ('030500 SE Ausgewählte Fragen des vergleichenden Verfassungsrechts');
INSERT INTO course (name) VALUES ('030578 MC Price Media Law Moot Court');
INSERT INTO course (name) VALUES ('030665 SE Seminar aus öffentlichem Recht (Verfassungsrecht: Grund- und Menschenrechte)');
INSERT INTO course (name) VALUES ('030060 VO Patentrecht I');
INSERT INTO course (name) VALUES ('030290 VO Geistiges Eigentum');
INSERT INTO course (name) VALUES ('030292 VO Gentechnikrecht');
INSERT INTO course (name) VALUES ('030438 KU Introduction into European IT-Law');
INSERT INTO course (name) VALUES ('030529 VO Grundlagen des Technologierechts I');
INSERT INTO course (name) VALUES ('030597 KU Künstliche Intelligenz und Recht');
INSERT INTO course (name) VALUES ('010102 FS Künstliche Intelligenz');
INSERT INTO course (name) VALUES ('030048 KU E-Commerce');
INSERT INTO course (name) VALUES ('030088 KU Arzneimittel- und Apothekenrecht');
INSERT INTO course (name) VALUES ('030239 SE European and International Business and Technology Law Seminar');
INSERT INTO course (name) VALUES ('030249 KU Europäisches und österreichisches Kartellrecht');
INSERT INTO course (name) VALUES ('030250 SE Seminar: Aktuelle Fragen des IT-Rechts für Diplomand*innen');
INSERT INTO course (name) VALUES ('030258 KU Programmieren für Jurist*innen');
INSERT INTO course (name) VALUES ('030372 KU Urheberrecht und elektronische Medien');
INSERT INTO course (name) VALUES ('030379 MC Manfred Lachs Space Law Moot Court');
INSERT INTO course (name) VALUES ('030464 SE Algorithmen der Verwaltung');
INSERT INTO course (name) VALUES ('030481 KU Startup Clinic');
INSERT INTO course (name) VALUES ('030518 KU General Legal Framework of the Use of Outer Space Technologies');
INSERT INTO course (name) VALUES ('030522 KU Aktuelle rechtliche Fragen zu Innovation und Digitalisierung');
INSERT INTO course (name) VALUES ('030543 KU Regulierung elektronischer Kommunikationsnetze und -dienste');
INSERT INTO course (name) VALUES ('030578 MC Price Media Law Moot Court');
INSERT INTO course (name) VALUES ('030587 KU Softwarerecht');
INSERT INTO course (name) VALUES ('030210 KU Folgt das Recht der Politik?');
INSERT INTO course (name) VALUES ('030326 SE Comparative Emergency Measures against the Pandemic');
INSERT INTO course (name) VALUES ('030371 SE Coronabedingte Herausforderungen an Gewaltenteilung, Rechtsschutz und Demokratie');
INSERT INTO course (name) VALUES ('030500 SE Ausgewählte Fragen des vergleichenden Verfassungsrechts');
INSERT INTO course (name) VALUES ('030537 KU Unseren Hass könnt ihr haben!');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030654 KU Emergency Laws in Comparative Perspective');
INSERT INTO course (name) VALUES ('030396 KU Einführung ins Kulturrecht');
INSERT INTO course (name) VALUES ('030072 KU Religions- und Weltanschauungsfreiheit in Österreich');
INSERT INTO course (name) VALUES ('030112 SE Recht des christlichen Ostens');
INSERT INTO course (name) VALUES ('030223 KU Persönlichkeitsrechte');
INSERT INTO course (name) VALUES ('030333 SE Jazyk a právo');
INSERT INTO course (name) VALUES ('030335 KU Der Künstler im Privat- und Strafrecht II');
INSERT INTO course (name) VALUES ('030336 SE Interkulturelles Strafrecht');
INSERT INTO course (name) VALUES ('030425 SE Seminar aus Rechtsphilosophie und Religionsrecht: Menschenrechte - Frauenrechte');
INSERT INTO course (name) VALUES ('030072 KU Religions- und Weltanschauungsfreiheit in Österreich');
INSERT INTO course (name) VALUES ('030054 VO Juden und Judenheit(en) in Österreich. Eine Rechtsgeschichte.');
INSERT INTO course (name) VALUES ('030112 SE Recht des christlichen Ostens');
INSERT INTO course (name) VALUES ('030194 KU Islam in Europa');
INSERT INTO course (name) VALUES ('030388 KU Comparative Law of Religion');
INSERT INTO course (name) VALUES ('030425 SE Seminar aus Rechtsphilosophie und Religionsrecht: Menschenrechte - Frauenrechte');
INSERT INTO course (name) VALUES ('030557 SE Die Ausgestaltung des Religionsunterrichts und des Ethikunterrichts');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030655 VO Introduction to Islamic Law');
INSERT INTO course (name) VALUES ('030673 KU Berühmte kirchliche Prozesse des Mittelalters');
INSERT INTO course (name) VALUES ('030032 KU Betreibermodelle in der Bauwirtschaft');
INSERT INTO course (name) VALUES ('030084 KU ÖNORM B2110');
INSERT INTO course (name) VALUES ('030122 KU Europäisches und Österreichisches Vergaberecht');
INSERT INTO course (name) VALUES ('030744 KU Haftung beim Bauvertrag');
INSERT INTO course (name) VALUES ('030064 KU Grundbuchsrecht und Liegenschaftsverträge in der Praxis');
INSERT INTO course (name) VALUES ('030091 KU Immobilienentwicklung');
INSERT INTO course (name) VALUES ('030155 KU Mediation im Bau- und Immobilienbereich');
INSERT INTO course (name) VALUES ('030521 KU Steuerliche Aspekte bei Liegenschaftstransaktionen');
INSERT INTO course (name) VALUES ('030697 KU Vertragsgestaltung I');
INSERT INTO course (name) VALUES ('030229 KU International Human Rights Law');
INSERT INTO course (name) VALUES ('030323 KU International Law in Domestic Courts');
INSERT INTO course (name) VALUES ('030516 KU International Organisations');
INSERT INTO course (name) VALUES ('030581 KU International Economic Law');
INSERT INTO course (name) VALUES ('030582 KU Foundations of International Law');
INSERT INTO course (name) VALUES ('030666 KU International Courts and Tribunals');
INSERT INTO course (name) VALUES ('030055 SE Seminar aus Völkerrecht: Völkerrechtliches Verfahrensrecht');
INSERT INTO course (name) VALUES ('030090 MC Jessup Moot Court, International Law Moot Court');
INSERT INTO course (name) VALUES ('030109 KU Human Rights II  (F)');
INSERT INTO course (name) VALUES ('030119 SE Advanced Research Seminar: Responsibility in International Law');
INSERT INTO course (name) VALUES ('030129 KU International Criminal Law and its Enforcement');
INSERT INTO course (name) VALUES ('030161 KU International and European Environmental Law (F)');
INSERT INTO course (name) VALUES ('030168 KU International Judicial Decisions and their Political Context');
INSERT INTO course (name) VALUES ('030170 KU Français juridique II');
INSERT INTO course (name) VALUES ('030213 KU Selected Issues of International Law');
INSERT INTO course (name) VALUES ('030238 SE Seminar aus Völkerrecht: Internationale Organisationen und die Corona Pandemie');
INSERT INTO course (name) VALUES ('030245 KU Introduction au droit international public');
INSERT INTO course (name) VALUES ('030317 KU Laws of Armed Conflict');
INSERT INTO course (name) VALUES ('030326 SE Comparative Emergency Measures against the Pandemic');
INSERT INTO course (name) VALUES ('030332 SE Grundlagen der Rechtsethik I');
INSERT INTO course (name) VALUES ('030379 MC Manfred Lachs Space Law Moot Court');
INSERT INTO course (name) VALUES ('030393 SE Seminar aus Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030423 SE Seminar aus Rechtsinformatik');
INSERT INTO course (name) VALUES ('030455 KU CISG at 40 - Course on Transnational Commercial Law (in cooperation with UNCITRAL)');
INSERT INTO course (name) VALUES ('030514 KU Principles of Procedure in Public International Law');
INSERT INTO course (name) VALUES ('030518 KU General Legal Framework of the Use of Outer Space Technologies');
INSERT INTO course (name) VALUES ('030539 KU Principles of International Law');
INSERT INTO course (name) VALUES ('030570 SE Seminar aus Völkerrecht: Pandemien im Völkerrecht');
INSERT INTO course (name) VALUES ('030579 KU The International Law of Territory');
INSERT INTO course (name) VALUES ('030585 KU Law and Economics of Public International Law');
INSERT INTO course (name) VALUES ('030606 MC International Investment Arbitration Moot Court');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030654 KU Emergency Laws in Comparative Perspective');
INSERT INTO course (name) VALUES ('030071 KU Menschenrechtliche und europarechtliche Grundlagen von Gleichheit und Nichtdiskriminierung');
INSERT INTO course (name) VALUES ('030099 KU Zivilrechtliche Aspekte des Gleichbehandlungsrechts');
INSERT INTO course (name) VALUES ('030117 KU Equality/Diversity');
INSERT INTO course (name) VALUES ('030240 KU Diskriminierungsschutz - Implementierung, Bewusstsein und Argumentationstechnik');
INSERT INTO course (name) VALUES ('030214 KU Praktische Rechtsdurchsetzung: Behörden und Verfahren - Prozessspiel');
INSERT INTO course (name) VALUES ('030237 KU Behindertengleichstellung');
INSERT INTO course (name) VALUES ('030476 KU Equality und Diversity in der betrieblichen Organisation');
INSERT INTO course (name) VALUES ('030240 KU Diskriminierungsschutz - Implementierung, Bewusstsein und Argumentationstechnik');
INSERT INTO course (name) VALUES ('030336 SE Interkulturelles Strafrecht');
INSERT INTO course (name) VALUES ('030118 KU Investigativer Journalismus im Rechtsstaat');
INSERT INTO course (name) VALUES ('030123 KU Anglo-Amerikanische Rechtssprache III');
INSERT INTO course (name) VALUES ('030143 KU Anglo-Amerikanische Rechtssprache V');
INSERT INTO course (name) VALUES ('030262 KU International Legal English I');
INSERT INTO course (name) VALUES ('030440 KU Anglo-Amerikanische Rechtssprache I');
INSERT INTO course (name) VALUES ('030561 KU International Legal English II');
INSERT INTO course (name) VALUES ('030563 KU International Legal English II');
INSERT INTO course (name) VALUES ('030577 KU International Legal English I');
INSERT INTO course (name) VALUES ('030594 KU International Legal English I');
INSERT INTO course (name) VALUES ('030619 KU International Legal English I');
INSERT INTO course (name) VALUES ('030005 SE Moot Court aus International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030090 MC Jessup Moot Court, International Law Moot Court');
INSERT INTO course (name) VALUES ('030317 KU Laws of Armed Conflict');
INSERT INTO course (name) VALUES ('030326 SE Comparative Emergency Measures against the Pandemic');
INSERT INTO course (name) VALUES ('030385 KU Drafting and Negotiating Cross-border M &amp; A and Joint Venture Contracts');
INSERT INTO course (name) VALUES ('030568 KU Discussion, Negotiation and Presentation in English');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030654 KU Emergency Laws in Comparative Perspective');
INSERT INTO course (name) VALUES ('030737 KU Case studies: Mergers &amp; Acquisitions');
INSERT INTO course (name) VALUES ('030109 KU Human Rights II  (F)');
INSERT INTO course (name) VALUES ('030119 SE Advanced Research Seminar: Responsibility in International Law');
INSERT INTO course (name) VALUES ('030129 KU International Criminal Law and its Enforcement');
INSERT INTO course (name) VALUES ('030132 KU The Austrian Legal System - an overview');
INSERT INTO course (name) VALUES ('030161 KU International and European Environmental Law (F)');
INSERT INTO course (name) VALUES ('030213 KU Selected Issues of International Law');
INSERT INTO course (name) VALUES ('030229 KU International Human Rights Law');
INSERT INTO course (name) VALUES ('030239 SE European and International Business and Technology Law Seminar');
INSERT INTO course (name) VALUES ('030309 SE European Union Law Seminar');
INSERT INTO course (name) VALUES ('030323 KU International Law in Domestic Courts');
INSERT INTO course (name) VALUES ('030356 KU Introduction to English Contract and Tort Law');
INSERT INTO course (name) VALUES ('030438 KU Introduction into European IT-Law');
INSERT INTO course (name) VALUES ('030455 KU CISG at 40 - Course on Transnational Commercial Law (in cooperation with UNCITRAL)');
INSERT INTO course (name) VALUES ('030516 KU International Organisations');
INSERT INTO course (name) VALUES ('030518 KU General Legal Framework of the Use of Outer Space Technologies');
INSERT INTO course (name) VALUES ('030539 KU Principles of International Law');
INSERT INTO course (name) VALUES ('030581 KU International Economic Law');
INSERT INTO course (name) VALUES ('030582 KU Foundations of International Law');
INSERT INTO course (name) VALUES ('030585 KU Law and Economics of Public International Law');
INSERT INTO course (name) VALUES ('030600 KU Introduction to European Union Law');
INSERT INTO course (name) VALUES ('030601 KU Free Movement of Persons in European Union Law');
INSERT INTO course (name) VALUES ('030603 SE Seminar aus Europarecht');
INSERT INTO course (name) VALUES ('030606 MC International Investment Arbitration Moot Court');
INSERT INTO course (name) VALUES ('030666 KU International Courts and Tribunals');
INSERT INTO course (name) VALUES ('030170 KU Français juridique II');
INSERT INTO course (name) VALUES ('030245 KU Introduction au droit international public');
INSERT INTO course (name) VALUES ('030547 KU Einführung in die französische Rechtssprache für Erasmus-Outgoings');
INSERT INTO course (name) VALUES ('030112 SE Recht des christlichen Ostens');
INSERT INTO course (name) VALUES ('030333 SE Jazyk a právo');
INSERT INTO course (name) VALUES ('030245 KU Introduction au droit international public');
INSERT INTO course (name) VALUES ('030387 KU Legal Literacy: Recht einfach präsentieren');
INSERT INTO course (name) VALUES ('030395 KU Recht und Sprache in der Praxis');
INSERT INTO course (name) VALUES ('030463 KU Legal Literacy: Recht einfach präsentieren');
INSERT INTO course (name) VALUES ('030575 KU Refugee Law Clinic I (Asyl- und Asylverfahrensrecht)');
INSERT INTO course (name) VALUES ('030672 KU Workshop zum Verfassen juristischer Texte');
INSERT INTO course (name) VALUES ('030481 KU Startup Clinic');
INSERT INTO course (name) VALUES ('030575 KU Refugee Law Clinic I (Asyl- und Asylverfahrensrecht)');
INSERT INTO course (name) VALUES ('030005 SE Moot Court aus International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030006 KU Introduction to Negotiation');
INSERT INTO course (name) VALUES ('030036 KU European Competition Procedures');
INSERT INTO course (name) VALUES ('030039 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030090 MC Jessup Moot Court, International Law Moot Court');
INSERT INTO course (name) VALUES ('030109 KU Human Rights II  (F)');
INSERT INTO course (name) VALUES ('030119 SE Advanced Research Seminar: Responsibility in International Law');
INSERT INTO course (name) VALUES ('030123 KU Anglo-Amerikanische Rechtssprache III');
INSERT INTO course (name) VALUES ('030124 MC ICC International Commercial Mediation Moot Court');
INSERT INTO course (name) VALUES ('030129 KU International Criminal Law and its Enforcement');
INSERT INTO course (name) VALUES ('030132 KU The Austrian Legal System - an overview');
INSERT INTO course (name) VALUES ('030142 KU Legal Informatics');
INSERT INTO course (name) VALUES ('030143 KU Anglo-Amerikanische Rechtssprache V');
INSERT INTO course (name) VALUES ('030161 KU International and European Environmental Law (F)');
INSERT INTO course (name) VALUES ('030168 KU International Judicial Decisions and their Political Context');
INSERT INTO course (name) VALUES ('030170 KU Français juridique II');
INSERT INTO course (name) VALUES ('030174 KU Comparative Private International Law');
INSERT INTO course (name) VALUES ('030198 KU Mediation for Lawyers');
INSERT INTO course (name) VALUES ('030199 KU Course: "European Criminal Law"');
INSERT INTO course (name) VALUES ('030213 KU Selected Issues of International Law');
INSERT INTO course (name) VALUES ('030217 KU Comparative Corporate Law Theory and Economic Analysis');
INSERT INTO course (name) VALUES ('030229 KU International Human Rights Law');
INSERT INTO course (name) VALUES ('030233 KU Legal Writing');
INSERT INTO course (name) VALUES ('030234 KU European Labour and Social Security Law');
INSERT INTO course (name) VALUES ('030238 SE Seminar aus Völkerrecht: Internationale Organisationen und die Corona Pandemie');
INSERT INTO course (name) VALUES ('030239 SE European and International Business and Technology Law Seminar');
INSERT INTO course (name) VALUES ('030243 SE EU Asyl- und Migrationsrecht: Ausgewählte Problemfelder und Perspektiven');
INSERT INTO course (name) VALUES ('030244 VO European Union Internal Market Law');
INSERT INTO course (name) VALUES ('030245 KU Introduction au droit international public');
INSERT INTO course (name) VALUES ('030251 KU Introduction to Japanese Law');
INSERT INTO course (name) VALUES ('030259 SE Cinema and Human Rights');
INSERT INTO course (name) VALUES ('030262 KU International Legal English I');
INSERT INTO course (name) VALUES ('030274 SE "Judentümer"- Rechts-, Politik-, Sozial- und Kulturgeschichte der Juden in der Neuzeit');
INSERT INTO course (name) VALUES ('030275 MC International Roman Law Moot Court');
INSERT INTO course (name) VALUES ('030277 KU Introducción al derecho espanol y terminología jurídica espanola');
INSERT INTO course (name) VALUES ('030297 KU Public Markets, Securities Regulation and Corporate Governance');
INSERT INTO course (name) VALUES ('030298 SE Seminar aus Zivilverfahrensrecht - Schwerpunkt: International Dispute Resolution');
INSERT INTO course (name) VALUES ('030309 SE European Union Law Seminar');
INSERT INTO course (name) VALUES ('030316 KU Women in Law (Part A): Women in Legal Professions - Contemporary Issues');
INSERT INTO course (name) VALUES ('030317 KU Laws of Armed Conflict');
INSERT INTO course (name) VALUES ('030323 KU International Law in Domestic Courts');
INSERT INTO course (name) VALUES ('030325 KU Hasskriminalität im österreichischen und internationalen Kontext');
INSERT INTO course (name) VALUES ('030326 SE Comparative Emergency Measures against the Pandemic');
INSERT INTO course (name) VALUES ('030327 KU EU Internal Market and Public Procurement Law');
INSERT INTO course (name) VALUES ('030333 SE Jazyk a právo');
INSERT INTO course (name) VALUES ('030356 KU Introduction to English Contract and Tort Law');
INSERT INTO course (name) VALUES ('030370 KU Il Diritto Pubblico di Roma dalla Monarchia alla Repubblica (VIII-I sec. a.C.)');
INSERT INTO course (name) VALUES ('030379 MC Manfred Lachs Space Law Moot Court');
INSERT INTO course (name) VALUES ('030385 KU Drafting and Negotiating Cross-border M &amp; A and Joint Venture Contracts');
INSERT INTO course (name) VALUES ('030388 KU Comparative Law of Religion');
INSERT INTO course (name) VALUES ('030403 VO International Commercial Arbitration');
INSERT INTO course (name) VALUES ('030410 KU Europäische Wettbewerbspolitik');
INSERT INTO course (name) VALUES ('030416 SE Europäisches Umweltrecht: Klimaschutz und Energie');
INSERT INTO course (name) VALUES ('030438 KU Introduction into European IT-Law');
INSERT INTO course (name) VALUES ('030440 KU Anglo-Amerikanische Rechtssprache I');
INSERT INTO course (name) VALUES ('030455 KU CISG at 40 - Course on Transnational Commercial Law (in cooperation with UNCITRAL)');
INSERT INTO course (name) VALUES ('030472 MC European Law Moot Court Competition');
INSERT INTO course (name) VALUES ('030495 UE Practical exercises in EU-Law');
INSERT INTO course (name) VALUES ('030502 KU An Introduction to Legal Theory');
INSERT INTO course (name) VALUES ('030509 SE Seminar aus Zivilrecht und IPR / Civilno pravo in mednarodno zasebno pravo');
INSERT INTO course (name) VALUES ('030514 KU Principles of Procedure in Public International Law');
INSERT INTO course (name) VALUES ('030516 KU International Organisations');
INSERT INTO course (name) VALUES ('030518 KU General Legal Framework of the Use of Outer Space Technologies');
INSERT INTO course (name) VALUES ('030526 KU EU Judicature');
INSERT INTO course (name) VALUES ('030533 KU International Business Transactions');
INSERT INTO course (name) VALUES ('030534 SE COVID-19 and International Dispute Resolution');
INSERT INTO course (name) VALUES ('030539 KU Principles of International Law');
INSERT INTO course (name) VALUES ('030540 KU Introduction to Legal English for Erasmus Students -English Language in European &amp; International Law');
INSERT INTO course (name) VALUES ('030541 KU Comparative Constitutional Studies');
INSERT INTO course (name) VALUES ('030547 KU Einführung in die französische Rechtssprache für Erasmus-Outgoings');
INSERT INTO course (name) VALUES ('030552 KU Einführung in die italienische Rechtssprache');
INSERT INTO course (name) VALUES ('030561 KU International Legal English II');
INSERT INTO course (name) VALUES ('030563 KU International Legal English II');
INSERT INTO course (name) VALUES ('030566 MC Ius Commune Moot Court');
INSERT INTO course (name) VALUES ('030568 KU Discussion, Negotiation and Presentation in English');
INSERT INTO course (name) VALUES ('030570 SE Seminar aus Völkerrecht: Pandemien im Völkerrecht');
INSERT INTO course (name) VALUES ('030577 KU International Legal English I');
INSERT INTO course (name) VALUES ('030578 MC Price Media Law Moot Court');
INSERT INTO course (name) VALUES ('030579 KU The International Law of Territory');
INSERT INTO course (name) VALUES ('030580 KU Private Law Theory');
INSERT INTO course (name) VALUES ('030581 KU International Economic Law');
INSERT INTO course (name) VALUES ('030582 KU Foundations of International Law');
INSERT INTO course (name) VALUES ('030585 KU Law and Economics of Public International Law');
INSERT INTO course (name) VALUES ('030589 KU Handschriften und Quellen - Jüdische Sprachen (Hebräisch, Judendeutsch und Jiddisch)');
INSERT INTO course (name) VALUES ('030594 KU International Legal English I');
INSERT INTO course (name) VALUES ('030600 KU Introduction to European Union Law');
INSERT INTO course (name) VALUES ('030601 KU Free Movement of Persons in European Union Law');
INSERT INTO course (name) VALUES ('030603 SE Seminar aus Europarecht');
INSERT INTO course (name) VALUES ('030606 MC International Investment Arbitration Moot Court');
INSERT INTO course (name) VALUES ('030619 KU International Legal English I');
INSERT INTO course (name) VALUES ('030621 KU Handschriften und Quellen, Deutsch und Latein');
INSERT INTO course (name) VALUES ('030652 KU EU Constitutional Law: The Evolving Constitution of the European Union');
INSERT INTO course (name) VALUES ('030653 KU Comparative Constitutional Law of the Middle East');
INSERT INTO course (name) VALUES ('030654 KU Emergency Laws in Comparative Perspective');
INSERT INTO course (name) VALUES ('030655 VO Introduction to Islamic Law');
INSERT INTO course (name) VALUES ('030666 KU International Courts and Tribunals');
INSERT INTO course (name) VALUES ('030667 KU Introduction to Jewish Law in Context: Legal Sources, Time &amp; Space');
INSERT INTO course (name) VALUES ('030697 KU Vertragsgestaltung I');
INSERT INTO course (name) VALUES ('030737 KU Case studies: Mergers &amp; Acquisitions');
INSERT INTO course (name) VALUES ('380034 SE Dissertant*innenseminar zur Präsentation des Dissertationsvorhabens');
INSERT INTO course (name) VALUES ('030015 SE Spinozas Rechtsdenken zwischen Religion und Staat');
INSERT INTO course (name) VALUES ('030038 KU Geschichte des österreichischen Justizrechts - Geltung und Ausstrahlung nach 1918');
INSERT INTO course (name) VALUES ('030041 VO Römische Rechtsgeschichte und ausgewählte Gebiete des Personen- und Familienrechts');
INSERT INTO course (name) VALUES ('030054 VO Juden und Judenheit(en) in Österreich. Eine Rechtsgeschichte.');
INSERT INTO course (name) VALUES ('030078 SE Seminar: Rechtsgeschichte der Wirtschaft');
INSERT INTO course (name) VALUES ('030112 SE Recht des christlichen Ostens');
INSERT INTO course (name) VALUES ('030141 KU Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030191 KU Kurs gegenchronologische Verfassungsgeschichte 20. Jhdt.');
INSERT INTO course (name) VALUES ('030194 KU Islam in Europa');
INSERT INTO course (name) VALUES ('030197 SE Geschichte des Medizinrechts');
INSERT INTO course (name) VALUES ('030256 SE Seminar aus europäischer und vergleichender Rechtsgeschichte für Diplomand*innen u. Dissertant*innen');
INSERT INTO course (name) VALUES ('030274 SE "Judentümer"- Rechts-, Politik-, Sozial- und Kulturgeschichte der Juden in der Neuzeit');
INSERT INTO course (name) VALUES ('030275 MC International Roman Law Moot Court');
INSERT INTO course (name) VALUES ('030285 VO Ringvorlesung "Antike Rechtsgeschichte"');
INSERT INTO course (name) VALUES ('030299 KU Rechtsgeschichte des vormodernen Europa');
INSERT INTO course (name) VALUES ('030311 VO Frauen im Recht (Teil B): Frauen in den Rechtsberufen - Rechtsgeschichte');
INSERT INTO course (name) VALUES ('030314 SE Nationsbildung und Verfassungsentwicklung in Europa 2. Teil');
INSERT INTO course (name) VALUES ('030370 KU Il Diritto Pubblico di Roma dalla Monarchia alla Repubblica (VIII-I sec. a.C.)');
INSERT INTO course (name) VALUES ('030373 VO Aus der Werkstatt: Aktuelle rechtshistorische Forschungen am Juridicum');
INSERT INTO course (name) VALUES ('030390 KU Einführung in Rechtsordnungen der ehemaligen sozialistischen Länder');
INSERT INTO course (name) VALUES ('030392 KU Die römische Gesellschaft');
INSERT INTO course (name) VALUES ('030393 SE Seminar aus Völkerrechtsgeschichte');
INSERT INTO course (name) VALUES ('030401 KU Spinozas Rechtsethik zwischen Sicherheit und Freiheit');
INSERT INTO course (name) VALUES ('030418 SE Seminar: Große Prozesse');
INSERT INTO course (name) VALUES ('030420 VO Geschichte der Grund- und Menschenrechte');
INSERT INTO course (name) VALUES ('030426 KU Politische Philosophie und Philosophie des Rechts');
INSERT INTO course (name) VALUES ('030504 SE Seminar aus Arbeitsrecht und Rechtsgeschichte');
INSERT INTO course (name) VALUES ('030524 SE Aktuelle Forschungen im Bereich des Röm. Rechts u. seiner Fortwirkung in den geltenden Privatrechten');
INSERT INTO course (name) VALUES ('030526 KU EU Judicature');
INSERT INTO course (name) VALUES ('030528 SE Seminar: Normsetzung und Rechtsprechung im Nationalsozialismus. Ausgewählte Aspekte');
INSERT INTO course (name) VALUES ('030549 SE Seminar aus Römischem Recht - Kaufen wie in Troja');
INSERT INTO course (name) VALUES ('030557 SE Die Ausgestaltung des Religionsunterrichts und des Ethikunterrichts');
INSERT INTO course (name) VALUES ('030559 KU Globalisierung und Rechtspluralismus');
INSERT INTO course (name) VALUES ('030560 SE Fritz Bauer oder: Auschwitz vor Gericht');
INSERT INTO course (name) VALUES ('030566 MC Ius Commune Moot Court');
INSERT INTO course (name) VALUES ('030589 KU Handschriften und Quellen - Jüdische Sprachen (Hebräisch, Judendeutsch und Jiddisch)');
INSERT INTO course (name) VALUES ('030613 KU Geschichte des Strafrechts und des Strafverfahrensrechts');
INSERT INTO course (name) VALUES ('030621 KU Handschriften und Quellen, Deutsch und Latein');
INSERT INTO course (name) VALUES ('030652 KU EU Constitutional Law: The Evolving Constitution of the European Union');
INSERT INTO course (name) VALUES ('030667 KU Introduction to Jewish Law in Context: Legal Sources, Time &amp; Space');
INSERT INTO course (name) VALUES ('030673 KU Berühmte kirchliche Prozesse des Mittelalters');
INSERT INTO course (name) VALUES ('030684 SE SE ohne Generalthema');
INSERT INTO course (name) VALUES ('030707 SE Seminar aus Rechts- und Verfassungsgeschichte: Rechtspolitische Filme der Zwischenkriegszeit');
INSERT INTO course (name) VALUES ('030187 KU Rechtsterminologie lateinischen Ursprungs');
INSERT INTO course (name) VALUES ('030188 KU Rechtsterminologie lateinischen Ursprungs');
INSERT INTO course (name) VALUES ('030200 VO+UE Lateinische Formenlehre und Syntax');
INSERT INTO course (name) VALUES ('030320 VO+UE Lateinische Formenlehre und Syntax');
INSERT INTO course (name) VALUES ('030382 KU Rechtsterminologie lateinischen Ursprungs');
INSERT INTO course (name) VALUES ('030394 VO+UE Lateinische Formenlehre und Syntax');
INSERT INTO course (name) VALUES ('030723 VO+UE Lateinische Formenlehre und Syntax');
INSERT INTO course (name) VALUES ('STEOP: MP Einführung in die Rechtswissenschaften und ihre Methoden');
INSERT INTO course (name) VALUES ('FÜM I (schriftliche MP Europäische und internationale Grundlagen des Rechts)');
INSERT INTO course (name) VALUES ('MP Rechts- und Verfassungsgeschichte der neueren Zeit');
INSERT INTO course (name) VALUES ('MP Straf- und Strafprozessrecht');
INSERT INTO course (name) VALUES ('MP Bürgerliches Recht');
INSERT INTO course (name) VALUES ('FÜM II (schriftliche MP Privatrecht)');
INSERT INTO course (name) VALUES ('FÜM II (schriftliche MP Privatrecht)');
INSERT INTO course (name) VALUES ('MP Unternehmensrecht');
INSERT INTO course (name) VALUES ('MP Zivilverfahrensrecht');
INSERT INTO course (name) VALUES ('MP Arbeitsrecht und Sozialrecht');
INSERT INTO course (name) VALUES ('MP Verfassungsrecht');
INSERT INTO course (name) VALUES ('FÜM III (schriftliche MP Öffentliches Recht)');
INSERT INTO course (name) VALUES ('MP Europarecht');
INSERT INTO course (name) VALUES ('MP Völkerrecht');
INSERT INTO course (name) VALUES ('MP Steuerrecht');
