logging:
  file.name: ./log/backend.log
  level:
    root: INFO

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/juridicum
    username: kper
    password: kper

  flyway:
    validate-on-migrate: true
    encoding: UTF-8

  jpa:
    # Set this property to true if you want to see the executed queries
    show-sql: false
    #hibernate:
      #ddl-auto: none
    # Allows to fetch lazy properties outside of the original transaction. Although this sounds helpful, the property
    # is disabled since it breaks the principle of least astonishment and leads to bad performance. The learn more,
    # follow this link: https://bit.ly/2LaX9ku
    open-in-view: false
  mail:
    host: 127.0.0.1
    port: 1025
  security:
    auth:
      header: Authorization
      white-list:
        - /
        - /favicon.ico
        - /csrf
        - /h2-console/**
server:
  error:
    include-message: always

